name: Acceptance tests

on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu (Latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SweetPea
        uses: actions/checkout@v2
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
      - name: Run acceptance tests
        run: python3 -m pytest -p no:warnings acceptance

  macos:
    name: macOS (10.15)
    # NOTE: We explicitly use macOS 10.15 for clarity. As of this writing, the
    #       `macos-latest` runner is just an alias for `macos-10.15`. Big Sur is
    #       currently in early preview and is not publicly available.
    # TODO: Check back at the following page (under the `jobs.<job_id>.runs-on`
    #       heading) to see if we can update to Big Sur yet:
    #           https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: macos-10.15
    steps:
      - name: Checkout SweetPea
        uses: actions/checkout@v2
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
      - name: Run acceptance tests
        run: python3 -m pytest -p no:warnings acceptance

  windows:
    name: Windows (Latest)
    runs-on: windows-latest
    steps:
      - name: Checkout SweetPea
        uses: actions/checkout@v2
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
      - name: Run acceptance tests
        run: python3 -m pytest -p no:warnings acceptance
