name: Publish GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/_build/html/**'

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SweetPea
        uses: actions/checkout@v2
      - name: Publish static site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
